<?php
/**
 * This file contains the markup for the abandoned cart email continue shopping button.
 *
 * @since   1.36
 * @link    http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
 *
 * Example: theme/exchange/emails/abandoned-cart/cart-details.php
 */
?>
<tr>
	<td align="center">
		<!--[if mso]>
		<center>
			<table>
				<tr>
					<td width="640">
		<![endif]-->
		<table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 640px; background: <?php it_exchange( 'email', 'body-background-color' ); ?>; margin: 0 auto;" class="wrapper">
			<tbody>
			<tr>
				<td valign="top" style="padding: 20px 25px; font-family: 'Helvetica', Arial, sans-serif;">
					<a href="<?php it_exchange( 'abandoned-cart', 'reclaim-link' ); ?>" style="display: inline-block;width: 100%;text-align: center;text-decoration: none; color: <?php it_exchange( 'email', 'body-button-color' ); ?>;background: <?php it_exchange( 'email', 'body-highlight-color' ); ?>;padding: 20px 0;">
						<?php it_exchange( 'abandoned-cart', 'reclaim-link', 'format=label' ); ?>
					</a>
				</td>
			</tr>
			</tbody>
		</table>
		<!--[if mso]>
		</td></tr></table>
		</center>
		<![endif]-->
	</td>
</tr>
